queue:
  name: Hosted macOS
  demands: msbuild

variables:
  BuildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  inputs:
    restoreSolution: CameraPreview.sln

- task: MSBuild@1
  displayName: 'Build project CameraPrevew'
  inputs:
    solution: CameraPreview.sln
    msbuildArchitecture: x64
    configuration: '$(BuildConfiguration)'

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    arguments: .nuspecs/CameraPreview.nuspec
